// Signs the release build with Relay's own key instead of the Expo template's debug keystore.
//
// `android/` is regenerated by `expo prebuild`, so the change cannot live there. This plugin
// appends a block to `android/app/build.gradle` on every prebuild. The block holds no secret and
// no machine path: Gradle reads the key location and its passwords at build time from a
// properties file outside the repo (`RELAY_SIGNING_PROPERTIES`, or `~/.config/relay/signing.properties`).
//
// It appends rather than rewriting the template's `signingConfig signingConfigs.debug` line, so it
// does not depend on the template's exact text. A later `android {}` block wins in Gradle.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @generated relay-release-signing';
const END_MARKER = '// @end relay-release-signing';

const BLOCK = `
${MARKER} (mobile/plugins/withReleaseSigning.js)
def relaySigningFile = new File(System.getenv("RELAY_SIGNING_PROPERTIES") ?: System.getProperty("user.home") + "/.config/relay/signing.properties")
def relaySigning = new Properties()
if (relaySigningFile.exists()) {
    relaySigningFile.withInputStream { relaySigning.load(it) }
}
def relaySigningMissing = ["storeFile", "storePassword", "keyAlias", "keyPassword"].findAll { !relaySigning.getProperty(it)?.trim() }

android {
    signingConfigs {
        relayRelease {
            if (relaySigningFile.exists() && relaySigningMissing.isEmpty()) {
                def relayStore = new File(relaySigning.getProperty("storeFile"))
                // A relative storeFile is resolved next to the properties file.
                storeFile relayStore.isAbsolute() ? relayStore : new File(relaySigningFile.parentFile, relayStore.path)
                storePassword relaySigning.getProperty("storePassword")
                keyAlias relaySigning.getProperty("keyAlias")
                keyPassword relaySigning.getProperty("keyPassword")
            }
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.relayRelease
        }
    }
}

// Without the key there is no release build: the template's debug keystore is public.
gradle.taskGraph.whenReady { graph ->
    def signsRelease = graph.allTasks.any { it.project == project && it.name in ["packageRelease", "signReleaseBundle"] }
    if (signsRelease && !relaySigningFile.exists()) {
        throw new GradleException("Relay: no signing properties at " + relaySigningFile + ". Set RELAY_SIGNING_PROPERTIES or see mobile/README.md.")
    }
    if (signsRelease && !relaySigningMissing.isEmpty()) {
        throw new GradleException("Relay: signing properties missing required fields: " + relaySigningMissing.join(", "))
    }
}
${END_MARKER}
`;

function appendReleaseSigning(buildGradle) {
  const start = buildGradle.indexOf(MARKER);
  if (start < 0) return buildGradle + BLOCK;
  const markedEnd = buildGradle.indexOf(END_MARKER, start);
  let end;
  if (markedEnd >= 0) end = markedEnd + END_MARKER.length;
  else {
    // Upgrade the original generated block, which ended at this task-graph closure.
    const graph = buildGradle.indexOf('\ngradle.taskGraph.whenReady { graph ->', start);
    const closure = graph < 0 ? -1 : buildGradle.indexOf('\n}\n', graph);
    if (closure < 0) throw new Error('Relay: unrecognized generated signing block; run prebuild --clean.');
    end = closure + 2;
  }
  return buildGradle.slice(0, start) + BLOCK.trimStart() + buildGradle.slice(end).replace(/^\n/, '');
}

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: android/app/build.gradle is not Groovy; update the plugin.');
    }
    config.modResults.contents = appendReleaseSigning(config.modResults.contents);
    return config;
  });
}

module.exports = withReleaseSigning;
module.exports.MARKER = MARKER;
module.exports.appendReleaseSigning = appendReleaseSigning;
