const fs = require('node:fs');
const path = require('node:path');
const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
// The Avisos snapshot is encrypted with an AndroidKeyStore key that never leaves the device, so a
// restored copy can never be decrypted. expo-secure-store points the manifest at these two resource
// names; app resources override the library's files of the same name, keeping its SecureStore rule.
const SNAPSHOT = 'relay.notifications.private.v1.xml';
const rules = '    <include domain="sharedpref" path="."/>\n    <exclude domain="sharedpref" path="SecureStore"/>\n'
  + `    <exclude domain="sharedpref" path="${SNAPSHOT}"/>\n`;
const BACKUP_FILES = {
  'app/src/main/res/xml/secure_store_backup_rules.xml': `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by mobile/plugins/withRelayNotifications.js. -->\n<full-backup-content>\n${rules}</full-backup-content>\n`,
  'app/src/main/res/xml/secure_store_data_extraction_rules.xml': `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by mobile/plugins/withRelayNotifications.js. -->\n<data-extraction-rules>\n  <cloud-backup>\n${rules}  </cloud-backup>\n  <device-transfer>\n${rules}  </device-transfer>\n</data-extraction-rules>\n`,
};
function configureNotifications(value) {
  const manifest=value.manifest;
  manifest['uses-permission'] ??= [];
  if (!manifest['uses-permission'].some(item=>item.$['android:name']==='android.permission.POST_NOTIFICATIONS'))
    manifest['uses-permission'].push({$: {'android:name':'android.permission.POST_NOTIFICATIONS'}});
  manifest.queries ??= []; manifest.queries[0] ??= {}; manifest.queries[0].intent ??= [];
  for(const action of ['org.unifiedpush.android.distributor.REGISTER'])
    if(!manifest.queries[0].intent.some(item=>item.action?.some(row=>row.$['android:name']===action)))
      manifest.queries[0].intent.push({action:[{$:{'android:name':action}}]});
  return value;
}
module.exports = config => withDangerousMod(withAndroidManifest(config,config=>{config.modResults=configureNotifications(config.modResults);return config;}),['android',async config=>{
  for(const [name,xml] of Object.entries(BACKUP_FILES)){
    const file=path.join(config.modRequest.platformProjectRoot,name);
    await fs.promises.mkdir(path.dirname(file),{recursive:true});await fs.promises.writeFile(file,xml);
  }
  return config;
}]);
module.exports.configureNotifications=configureNotifications;
module.exports.BACKUP_FILES=BACKUP_FILES;
