// Lets the release app talk plain http:// to tailnet names (`*.ts.net`) and to nothing else.
//
// Android blocks cleartext by default for apps that target API 28+. The bridge serves plain HTTP on
// the tailnet (Tailscale already encrypts the link), so the app needs an exception, and it is scoped
// by domain: a Network Security Config with one `domain-config`. Not `usesCleartextTraffic`, which
// would allow http:// to any host. Decision in issue #11.
//
// A domain rule matches host names only: the tailnet IP (100.x) and the short machine name stay
// blocked. `src/core/connection.ts` warns about those URLs before the user tries them.
//
// `android/` is regenerated by `expo prebuild`, so the XML file is written and the manifest
// attribute is set on every prebuild.
//
// Only the explicit development variant adds exact loopback hosts so Relay Dev can reach Metro
// through adb reverse. Release never inherits these exceptions from the build mode or environment.
const fs = require('node:fs');
const path = require('node:path');

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const { resolveVariant } = require('../app.config');

const RESOURCE = '@xml/network_security_config';
const RESOURCE_FILE = 'app/src/main/res/xml/network_security_config.xml';

// Keep in step with CLEARTEXT_DOMAIN in src/core/connection.ts (a test checks it).
const CLEARTEXT_DOMAINS = ['ts.net'];

function networkSecurityConfigXml(variant = 'release') {
  const rules = CLEARTEXT_DOMAINS.map((host) => ({ host, includeSubdomains: true }));
  if (resolveVariant(variant) === 'development') {
    rules.push({ host: 'localhost', includeSubdomains: false }, { host: '127.0.0.1', includeSubdomains: false });
  }
  const domains = rules.map(({ host, includeSubdomains }) =>
    `        <domain includeSubdomains="${includeSubdomains}">${host}</domain>`).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <!-- Generated by mobile/plugins/withTailnetCleartext.js. Edit the plugin, not this file. -->
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
${domains}
    </domain-config>
</network-security-config>
`;
}

function setNetworkSecurityConfig(androidManifest) {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  const current = application.$['android:networkSecurityConfig'];
  if (current && current !== RESOURCE) {
    throw new Error(
      `withTailnetCleartext: android:networkSecurityConfig is already set to ${current}; Android takes only one.`,
    );
  }
  application.$['android:networkSecurityConfig'] = RESOURCE;
  return androidManifest;
}

function withTailnetCleartext(config, { variant = 'release' } = {}) {
  const xml = networkSecurityConfigXml(variant);
  config = withAndroidManifest(config, (config) => {
    config.modResults = setNetworkSecurityConfig(config.modResults);
    return config;
  });
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const file = path.join(config.modRequest.platformProjectRoot, RESOURCE_FILE);
      await fs.promises.mkdir(path.dirname(file), { recursive: true });
      await fs.promises.writeFile(file, xml);
      return config;
    },
  ]);
}

module.exports = withTailnetCleartext;
module.exports.CLEARTEXT_DOMAINS = CLEARTEXT_DOMAINS;
module.exports.RESOURCE = RESOURCE;
module.exports.networkSecurityConfigXml = networkSecurityConfigXml;
module.exports.setNetworkSecurityConfig = setNetworkSecurityConfig;
