/** Raw Agent response for the Markdown demo, based on screen 10·3. */
export const DEMO_MARKDOWN = [
  '## Qué pasó',
  '',
  'El mock de `createPool` se elevaba sobre el import. Más detalle en [issue #212][issue-212].',
  '',
  '- Corregí el test con **`vi.hoisted`**',
  '- Limpié la carpeta de build',
  '  - Conservé los archivos de configuración',
  '  - Comprobé el *directorio temporal*',
  '- La suite pasa completa',
  '',
  '> El job de CI usa caché; conviene invalidarla antes del próximo merge.',
  '',
  '| Suite | Antes | Ahora |',
  '| :--- | ---: | ---: |',
  '| Integración | 23/24 | **24/24** |',
  '| Unitarios | 112/112 | 112/112 |',
  '| Literal \\| separador | `a|b` | Sin cambios |',
  '',
  '```bash',
  'npm run ci:cache-clear',
  '  printf "**literal** | `sin formato`\\n"',
  '```',
  '',
  '### Siguiente paso',
  '',
  '1. Revisar el resultado',
  '   - Confirmar que no faltan pruebas',
  '2. Abrir el PR',
  '',
  'Código con sangría:',
  '',
  '    const resultado = "listo";',
  '    console.log(resultado);',
  '',
  'Escapes: \\*sin énfasis\\* y **negrita con _énfasis_**.',
  '',
  '¿Abro el PR con estos cambios?',
  '',
  '[issue-212]: https://github.com/AlejandroFloresArroyo/relay-app/issues/212',
].join('\n');
