#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
# Never let ask() consult an existing .env. No secret/environment writing helpers are used.
ENV_FILE=/dev/null
REPO_ROOT=$(cd -- "${BASH_SOURCE[0]%/*}/.." && pwd -P)

wizard_fail() { printf 'Error: %s\n' "$1" >&2; exit 1; }
wizard_help() {
  printf '%s\n' 'Uso: scripts/bridge-wizard.sh [--check|--help]' \
    'Wizard interactivo Linux para un Hermes existente; no instala ni cambia Hermes.' \
    '--check: comprueba requisitos y capacidades V3 (relayd doctor) sin configurar servicios ni leer secretos.' \
    '--plan <raíz-Hermes> <CLI-absoluta> <perfiles-separados-por-comas> <puerto> [--supervisor] [--files] [--web] [--browser-habitual]:' \
    '  valida rutas y opciones V3 y muestra el comando; no ejecuta la instalación. Guía V3: docs/v3-install.md.'
}
wizard_path() {
  local value=$1 kind=$2 component cursor=''
  [[ $value == /* && $value != / && $value != */ && $value != *//* && $value != *' ' && ! $value =~ [[:cntrl:]] ]] || wizard_fail 'Usa rutas absolutas normalizadas sin caracteres de control.'
  local parts; IFS=/ read -ra parts <<< "$value"
  for component in "${parts[@]}"; do
    [[ -n $component ]] || continue
    [[ $component != . && $component != .. ]] || wizard_fail 'No se aceptan componentes . o .. en las rutas.'
    cursor+="/$component"
    [[ ! -L $cursor ]] || wizard_fail 'La ruta contiene un enlace simbólico; selecciona su ruta física.'
  done
  if [[ $kind == directory ]]; then [[ -d $value ]] || wizard_fail 'No existe el directorio seleccionado.'
  else [[ -f $value && -x $value ]] || wizard_fail 'La CLI seleccionada debe ser un archivo ejecutable existente.'; fi
}
wizard_selection() {
  wizard_path "$WIZARD_HERMES_HOME" directory; wizard_path "$WIZARD_HERMES_BIN" executable
  [[ ${#WIZARD_PROFILES} -le 8192 && $WIZARD_PROFILES =~ ^[A-Za-z0-9][A-Za-z0-9._-]*(,[A-Za-z0-9][A-Za-z0-9._-]*)*$ ]] || wizard_fail 'Indica IDs de Agente separados por comas, sin espacios ni rutas.'
  [[ $WIZARD_PORT =~ ^[0-9]{1,5}$ ]] && (( 10#$WIZARD_PORT >= 1 && 10#$WIZARD_PORT <= 65535 )) || wizard_fail 'El puerto debe estar entre 1 y 65535.'
  local profiles profile; IFS=, read -ra profiles <<< "$WIZARD_PROFILES"
  (( ${#profiles[@]} <= 128 )) || wizard_fail 'Se admiten hasta 128 IDs de Agente.'
  for profile in "${profiles[@]}"; do
    [[ $profile == default ]] || wizard_path "$WIZARD_HERMES_HOME/profiles/$profile" directory
  done
}
wizard_check() {
  "$REPO_ROOT/scripts/prepare-dev.sh" --check
  local program
  for program in systemctl loginctl tailscale; do command -v "$program" >/dev/null 2>&1 || wizard_fail "Falta $program; el wizard no lo instala."; done
  [[ -n ${XDG_RUNTIME_DIR:-} && -d $XDG_RUNTIME_DIR ]] || wizard_fail 'Se necesita XDG_RUNTIME_DIR y una sesión systemd de usuario.'
  [[ -x $REPO_ROOT/bridge/relayd && -r $REPO_ROOT/bridge/src/main.ts ]] || wizard_fail 'No se encontró un checkout completo del Puente.'
  say 'Requisitos locales presentes. relayd setup comprobará la sesión systemd y la conexión Tailscale al ejecutarlo.'
  say 'Capacidades V3 (relayd doctor, solo lectura):'
  if ! "$REPO_ROOT/bridge/relayd" doctor; then
    note 'Las herramientas V3 son opcionales: el Puente se instala sin ellas. Cada línea «falta» dice cómo prepararla.'
  fi
}
# V3 tools the person chose; --browser-habitual is served next to the supervisor's environments.
wizard_v3_flags() {
  local flag seen=' '
  for flag in "$@"; do
    case $flag in --supervisor|--files|--web|--browser-habitual) ;; *) wizard_fail 'Opciones V3 válidas: --supervisor, --files, --web y --browser-habitual.' ;; esac
    [[ $seen != *" $flag "* ]] || wizard_fail 'Cada opción V3 se indica una sola vez.'
    seen+="$flag "
  done
  [[ $seen != *' --browser-habitual '* || $seen == *' --supervisor '* ]] || wizard_fail '--browser-habitual necesita --supervisor.'
}
wizard_command() {
  printf '  (cd %q && HERMES_HOME=%q HERMES_BIN=%q RELAY_PORT=%q ./relayd' "$REPO_ROOT/bridge" "$WIZARD_HERMES_HOME" "$WIZARD_HERMES_BIN" "$WIZARD_PORT"
  printf ' %q' "${WIZARD_SETUP_ARGS[@]}"; printf ')\n'
}
case "${1:-}" in
  --help|-h) (( $# == 1 )) || { wizard_help >&2; exit 2; }; wizard_help; exit 0 ;;
  --check) (( $# == 1 )) || { wizard_help >&2; exit 2; }; wizard_check; exit 0 ;;
  --plan)
    (( $# >= 5 )) || { wizard_help >&2; exit 2; }
    WIZARD_HERMES_HOME=$2; WIZARD_HERMES_BIN=$3; WIZARD_PROFILES=$4; WIZARD_PORT=$5; shift 5
    wizard_selection; wizard_v3_flags "$@"; WIZARD_SETUP_ARGS=(setup "$@"); wizard_command; exit 0 ;;
  '') (( $# == 0 )) || { wizard_help >&2; exit 2; } ;;
  *) wizard_help >&2; exit 2 ;;
esac
[[ -t 0 && -t 1 ]] || wizard_fail 'Ejecuta el wizard en una terminal interactiva; para inspección usa --check o --plan.'

banner 'Instalar el Puente junto a tu Hermes actual'
say 'No guarda respuestas del wizard ni lee .env; al repetirlo vuelve a elegir las rutas.'
say 'No se pedirán claves. Las operaciones de servicio requieren tu confirmación.'

stage 'Comprobar requisitos'
wizard_check
say 'Si falta algo, prepáralo tú y vuelve a ejecutar el wizard. No se instala software del sistema.'
pause 'Pulsa Enter para seleccionar tu instalación existente.'

stage 'Seleccionar Hermes existente y Agentes'
say 'Usa la raíz física de tu Hermes ya instalado, no la carpeta de un perfil individual.'
say 'La ruta del CLI debe ser absoluta. Puedes localizarla tú con command -v hermes; no se ejecutará para consultar su versión.'
ask WIZARD_HERMES_HOME 'Raíz absoluta de Hermes existente:'
ask WIZARD_HERMES_BIN 'Ruta física absoluta de su CLI ejecutable:'
ask WIZARD_PROFILES 'IDs de Agente que comprobarás después (por ejemplo default,dev):'
ask WIZARD_PORT 'Puerto del Puente (habitualmente 8650):'
wizard_selection
say 'El Puente descubre todos los perfiles de esa raíz. Esta lista solo guía tu comprobación; no crea ni filtra Agentes.'
say "Agentes que comprobarás: $WIZARD_PROFILES"

stage 'Preparar el Puente'
say "El servicio ejecutará este checkout: $REPO_ROOT/bridge"
say 'El Puente no tiene dependencias npm de ejecución: no necesita instalar Hermes ni ejecutar npm ci para arrancar.'
say 'Para desarrollar, usa scripts/prepare-dev.sh y scripts/gate.sh por separado.'
warn 'Si ya existe configuración privada del Puente, revísala tú antes de continuar: sus variables prevalecen sobre los valores de la unidad. El wizard no la lee.'
pause 'Pulsa Enter cuando hayas comprobado que esta es la instalación que quieres usar.'

stage 'Elegir herramientas V3 (opcional)'
say 'Terminal, archivos, webs y navegador habitual se activan por separado; sin ellos el Puente funciona como hasta ahora.'
say 'Los requisitos que faltan aparecieron en «Comprobar requisitos». Guía completa: docs/v3-install.md.'
WIZARD_V3=()
note 'Terminal: el supervisor corre en su propia unidad; antes compila node-pty con (cd supervisor && npm run setup).'
if confirm '¿Instalar el supervisor y activar la terminal (--supervisor)?'; then WIZARD_V3+=(--supervisor); fi
if confirm '¿Activar el explorador de archivos (--files)?'; then WIZARD_V3+=(--files); fi
note 'Webs: cada aplicación se publica a mano con Tailscale Services; relayd web muestra la orden. Requiere pasos de consola de la tailnet.'
if confirm '¿Activar las webs del Servidor (--web)?'; then WIZARD_V3+=(--web); fi
if [[ " ${WIZARD_V3[*]} " == *' --supervisor '* ]]; then
  note 'Navegador habitual: registra el adaptador con ./relayd browser google-chrome y carga tú la extensión en chrome://extensions.'
  if confirm '¿Activar el navegador habitual (--browser-habitual)?'; then WIZARD_V3+=(--browser-habitual); fi
fi
wizard_v3_flags "${WIZARD_V3[@]}"

stage 'Revisar el servicio de usuario'
say 'setup conserva la configuración privada existente, crea la unidad si falta, la habilita e inicia el Puente si está inactivo.'
say 'Una unidad distinta exige reemplazo explícito; el Puente activo no se reinicia por defecto.'
warn 'Si sustituyes la unidad sin reiniciar el Puente activo, los valores nuevos esperan al próximo arranque; el QR corresponde al proceso actual.'
say 'Reiniciar el Puente nunca termina las terminales: viven en el supervisor, que setup no reinicia.'
say 'No se modifica el gateway de Hermes, Tailscale, firewall ni linger.'
WIZARD_SETUP_ARGS=(setup "${WIZARD_V3[@]}")
if confirm '¿Permitir sustituir una unidad existente distinta (--replace-service)?'; then WIZARD_SETUP_ARGS+=(--replace-service); fi
if confirm '¿Reiniciar explícitamente el Puente si está activo (--restart)?'; then WIZARD_SETUP_ARGS+=(--restart); fi
wizard_command
if confirm '¿Simular antes este comando con --dry-run (muestra las unidades y órdenes, no cambia nada)?'; then
  (cd -- "$REPO_ROOT/bridge" && HERMES_HOME="$WIZARD_HERMES_HOME" HERMES_BIN="$WIZARD_HERMES_BIN" RELAY_PORT="$WIZARD_PORT" ./relayd "${WIZARD_SETUP_ARGS[@]}" --dry-run) \
    || warn 'La simulación encontró un problema; el comando real fallaría igual. Corrígelo antes de continuar.'
fi
pause 'Pulsa Enter para pasar a la confirmación final y al emparejamiento.'

stage 'Ejecutar y emparejar manualmente'
say 'Abre Relay en el teléfono, conectado a tu tailnet. setup mostrará su dirección y un QR/código de un solo uso.'
say 'Escanéalo o escribe dirección y código en Relay. No copies códigos a logs o tickets.'
wizard_command
if ! confirm '¿Ejecutar exactamente este comando e instalar/habilitar el servicio del Puente?'; then say 'Instalación no ejecutada. Puedes volver a abrir el wizard.'; exit 0; fi
if ! (cd -- "$REPO_ROOT/bridge" && HERMES_HOME="$WIZARD_HERMES_HOME" HERMES_BIN="$WIZARD_HERMES_BIN" RELAY_PORT="$WIZARD_PORT" ./relayd "${WIZARD_SETUP_ARGS[@]}"); then
  wizard_fail 'setup no terminó. Revisa los pasos que informó; no se fuerza reemplazo ni reinicio. Puedes repetir el wizard.'
fi
say 'El QR/código anterior caduca en cinco minutos; setup ya reutilizó el flujo de pair.'
say 'Comprueba los Agentes elegidos en Relay. Si necesitas otro código, ejecuta ./relayd pair desde bridge en una terminal interactiva.'
pause 'Pulsa Enter después de emparejar y comprobar el Servidor.'
finish
