import { View } from 'react-native';
import { act, fireEvent, screen, waitFor, within } from '@testing-library/react-native';
import { ServerConnectionStatus } from '@/ui/ServerConnectionStatus';
import { polling, seed, serverA, serverB } from '../support/fixtures';
import { renderApp } from '../support/renderApp';
import { json, networkError, requestsFor, respond } from '../support/transport';

test('retrying B, general refresh and scheduled polling preserve A suspension until A explicitly retries', async () => {
  seed([serverA, serverB]); polling(serverA); polling(serverB);
  respond(serverA.url, '/v1/agents', json({ error: { code: 'rate_limited', message: 'Fixture throttled' } }, 429));
  const app = renderApp(<><View testID="panel-A"><ServerConnectionStatus serverId="A" /></View><View testID="panel-B"><ServerConnectionStatus serverId="B" /></View></>);
  await app.ready();
  const panelA = within(screen.getByTestId('panel-A'));
  const panelB = within(screen.getByTestId('panel-B'));
  await waitFor(() => expect(panelA.getByText(/DEMASIADOS INTENTOS/)).toBeVisible());
  await waitFor(() => expect(app.probe.current!.snapshot('B').reachable).toBe(true));
  expect(app.probe.current!.snapshot('A').reachable).toBe(false);
  const countA = requestsFor(serverA.url).length;
  respond(serverB.url, '/v1/agents', networkError);
  await act(async () => { await jest.advanceTimersByTimeAsync(5000); });
  await waitFor(() => expect(panelB.getByText(/EL PUENTE RESPONDE/)).toBeVisible());
  expect(panelB.queryByText('SIN RESPUESTA')).toBeNull();
  expect(requestsFor(serverA.url)).toHaveLength(countA);
  expect(app.probe.current!.snapshot('B').reachable).toBe(false);
  const countB = requestsFor(serverB.url).length;
  polling(serverB);
  await act(async () => { fireEvent.press(panelB.getByText('Reintentar')); });
  await waitFor(() => expect(app.probe.current!.snapshot('B').reachable).toBe(true));
  expect(requestsFor(serverB.url).length).toBeGreaterThan(countB);
  expect(requestsFor(serverA.url)).toHaveLength(countA);
  await act(async () => { app.probe.current!.refresh(); });
  expect(requestsFor(serverA.url)).toHaveLength(countA);
  await act(async () => { await jest.advanceTimersByTimeAsync(5000); });
  expect(requestsFor(serverA.url)).toHaveLength(countA);
  polling(serverA);
  await act(async () => { fireEvent.press(panelA.getByText('Reintentar')); });
  await waitFor(() => expect(app.probe.current!.snapshot('A').reachable).toBe(true));
  expect(requestsFor(serverA.url).length).toBeGreaterThan(countA);
});
